# Copy this to .streamlit/secrets.toml and fill in your keys
OPENAI_API_KEY = "sk-..."
QDRANT_URL = "https://YOUR-CLUSTER.qdrant.tech"
QDRANT_API_KEY = "qdrant_xxx"

# Optional configuration (override defaults without code changes)
# Set the collection name to reuse across deployments
QDRANT_COLLECTION = "resumes"
# LLM and embedding models
MODEL_CHAT = "gpt-4o-mini"
MODEL_EMBEDDING = "text-embedding-3-small"
# Text splitter settings
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
# Retrieval top-k
TOP_K = 5
# Path to the CSV relative to the app file
RESUME_CSV_PATH = "Resume.csv"
