# Copy this to .streamlit/secrets.toml and fill in your keys
OPENAI_API_KEY = "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"
QDRANT_URL = "https://acb9e0ed-c7e4-4abc-9495-1382817b533e.europe-west3-0.gcp.cloud.qdrant.io"
QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.eaFw020zJyq7TXiUQTvpkkRgk-ZEvkvQBCiKAI0KHxo"

# Optional configuration (override defaults without code changes)
# Set the collection name to reuse across deployments
QDRANT_COLLECTION = "resumes"
# LLM and embedding models
MODEL_CHAT = "gpt-4o-mini"
MODEL_EMBEDDING = "text-embedding-3-small"
# Text splitter settings
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200
# Retrieval top-k
TOP_K = 5
# Path to the CSV relative to the app file
RESUME_CSV_PATH = "Resume.csv"
